import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased 
          relative min-h-screen bg-black overflow-x-hidden`}
      >
        {/* Cyberpunk Grid Background */}
        <div className="absolute inset-0 z-0 pointer-events-none">
          <div className="absolute inset-0 grid grid-cols-[repeat(20,1fr)] grid-rows-[repeat(20,1fr)] opacity-10">
            {[...Array(400)].map((_, i) => (
              <div
                key={i}
                className="border border-opacity-5 border-cyan-500"
              />
            ))}
          </div>

          {/* Neon Grid Lines */}
          <div className="absolute inset-0 pointer-events-none">
            <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-transparent via-transparent to-cyan-900/20 opacity-50"></div>
            <div className="absolute top-0 left-0 w-full h-full animate-pulse">
              <div className="absolute inset-0 bg-gradient-to-r from-transparent via-cyan-500/20 to-transparent opacity-30 animate-diagonal-move"></div>
              <div className="absolute inset-0 bg-gradient-to-b from-transparent via-cyan-500/20 to-transparent opacity-30 animate-diagonal-move-reverse"></div>
            </div>
          </div>
        </div>

        {/* Content Container */}
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
